# Generated by Django 4.1.7 on 2023-03-01 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('card_number', models.CharField(default='1234123412341234', max_length=16)),
                ('expiry_date', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCheese',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_cheeses', models.CharField(default='Mozzarella', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaCrust',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_crusts', models.CharField(choices=[('Normal', 'Normal'), ('Thin', 'Thin'), ('Thick', 'Thick'), ('Gluten Free', 'Gluten Free')], default='Normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSauce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_sauces', models.CharField(default='Tomato', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_sizes', models.CharField(default='Small', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaToppings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Pepperoni', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pizza_cheeses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mikes_Pizza.pizzacheese')),
                ('pizza_crusts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mikes_Pizza.pizzacrust')),
                ('pizza_sauces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mikes_Pizza.pizzasauce')),
                ('pizza_sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mikes_Pizza.pizzasize')),
                ('pizza_toppings', models.ManyToManyField(blank=True, related_name='topping', to='Mikes_Pizza.pizzatoppings')),
            ],
        ),
    ]
